#include <iostream>
#include "library.h"

int main(int argc, const char * argv[]) {

    Record record = {
        "PVAXOXODXS",
        "YLNGSWTCUJ",
        "CJQCNUUINM",
        "FFOUFOBQNO",
        "XASCNNEKVO",
        "TVMQQFCYXU",
        "WTDYRENVGH",
        "JERKJZKWVS",
        "WPSMFRJCZV",
        "CGZBXACTZO",
        "UDCATBVILN",
        "FIHETLNGTE",
        "NUOWTFQHIB",
        "ETUSLMRKKJ",
        "GLNSYGBGBF",
        "IWXNAPTSQF",
        "MJELDDXKSJ",
        "AKJVMCXXRU",
        "WRGTAQSIKA",
        "KKADSNCCCT",
        "SJASJYLELX",
        "LOTAHOQPDZ",
        "ULUPAIBZSY",
        "EFWCDDWAAZ",
        "QRQODKINRC",
        "ZFOVPLIBWL",
        "PHLHKVRANF",
        "GDYRFWQLFH",
        "DFLAEWKISA",
        "PMFCQQLDTD",
        "NVGAOSQHWL",
        "XGHOJAHCBM",
        "MVRSXKSGLR",
        "TJNVJTNHSP",
        "ARWPOKKYSF",
        "UHSWXIRJWL",
        "BRBZNPVDUI",
        "LTKTNDCUIP",
        "JZUHHWINES",
        "JJZFDEROHF",
        "RJJPIFIKIL",
        "VSTCEZVMCJ",
        "JFXPBXNKRG",
        "YDUNEHLBFH",
        "PIZBZJESGX",
        "LJWZCFRTLO",
        "ZHWHXFQNTK",
        "OAQCKQAPMX",
        "AWXKBWJTAT",
        "JIRFNWLDTH",
        "NRIJACFMER",
        "BOPXGLXUIH",
        "ODDEJLVYPJ",
        "JXQLJTATSV",
        "DKUXVZSDIP",
        "ONYUACOCJW",
        "DPDSXBGIOA",
        "FCULEJAPIE",
        "XILMUIULFU",
        "DRWTYTWJXW",
        "EEKIWVQSRS",
        "UHNHFYWXGA",
        "VAOKIVVZRI",
        "FKWXUWOMWX",
        "FXBQONQPSS",
        "HWOFYQSXWA",
        "LGSNDUZKSV",
        "ZODZRVJHBD",
        "XVHXFKNPED",
        "OAOVFUDPRO",
        "KFAVOLAPZT",
        "NHHJWYGFAU",
        "NOTZCDHENC",
        "AVCTBLMKKZ",
        "RTENCJQONR",
        "CDZEYEQXCM",
        "KTXLNJKBUA",
        "TKOFJKVVGP",
        "MMIRAVZVNL",
        "KHQTJLCDNV",
        "SHRTBDTTQS",
        "JKUQRNHJKY",
        "ZPJHCSUROM",
        "HTMIYLEJWJ",
        "SITORDZUHO",
        "TBNERQKRPG",
        "QUTNQZUVFZ",
        "RQQFGVUCVJ",
        "BSTCHPTTRQ",
        "UCUSUGBYBF",
        "FSDFMPVLPV",
        "VLAJINKUZN",
        "WKVNIAYUPQ",
        "KWEBQVGDEC",
        "VJKTWMWAGU",
        "HDOIRVMPUG",
        "RORZLNVSFC",
        "LPLXPEWUWO",
        "OQGNFQSDEP",
        "PVATWTUSOU",
    };

    std::cout << "fixed_len_sizeof result: ";
    std::cout << fixed_len_sizeof(&record);
    std::cout << "\n";
    return 0;
}
